<?php
/**
 * Request form view
 *
 * @category  Smile
 * @package   Smile\ContactUs
 * @author    Yaroslav Velychko <lijkbezorger@gmail.com>
 * @copyright 2018 Yaroslav Velychko
 */

use Magento\Framework\View\TemplateEngine\Php;
use Smile\ContactUs\Block\Form\RequestFormBlock;

/**
 * @var $block RequestFormBlock
 * @var $this Php
 */

?>

<h3><?php echo $block->getTitle() ?></h3>

<form action="<?php echo $block->getAction() ?>" method="<?php echo $block->getMethod() ?>"
      enctype="multipart/form-data">

    <fieldset class="fieldset create info">
        <div class="field required">
            <label for="topicField" class="label">Topic</label>
            <div class="control">
                <input id="topicField" type="text" name="topic"/>
            </div>

        </div>
        <div class="field required">
            <label for="emailField" class="label">Email</label>
            <div class="control">
                <input id="emailField" type="text" name="email"/>
            </div>

        </div>
        <div class="field required">
            <label for="requestTextField" class="label">Text</label>
            <div class="control">
                <textarea id="requestTextField" rows="4" cols="50" name="request_text"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Leave request">
                <span>Leave request</span>
            </button>
        </div>
    </div>
</form>
